server:
  port: 8090

  #DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/introductionSpring?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: introduction
    password: 1234
  thymeleaf:
    cache: false
